spring.application.name=proj45_springboot_layeredapp_springcore

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/finisher_batch
spring.datasource.username=root
spring.datasource.password=ramkumar







# jdbc.driver=com.mysql.cj.jdbc.Driver
# jdbc.url=jdbc:mysql://localhost:3306/finisher_batch
# jdbc.username=root
# jdbc.password=ramkumar

